### ISSUE TITLE
npm install isn't pulling in ./lib

### ISSUE THREAD

**Issue by erlswtshrt** [felixzapata/gulp-axe-core#1]
The install succeeds. ./lib isn't pulled into the module, but is required in index.js... fails with:

Error: Cannot find module './lib/reporter'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/project/node_modules/gulp-axe-core/index.js:10:16)

**Comment by felixzapata** [comment]
hi @erlswtshrt, thanks for report the issue. Fixed in [release 0.1.3](https://github.com/felixzapata/gulp-axe-core/releases/tag/0.1.3).
